version: '3'

services:
  frontend:
    image: node:18
    container_name: eaglenav-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app
    working_dir: /app
    command: npm start
    depends_on:
      - backend

  backend:
    image: node:18
    container_name: eaglenav-backend
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app
    working_dir: /app
    command: node server.js
    depends_on:
      - database

  database:
    image: mongo
    container_name: eaglenav-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
